name: Build and test on pull request

on:
    pull_request:
        branches: ['*']

jobs:
    automation-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build services
              run: npm run build

            - name: Run tests
              run: npm test
